"""empty message

Revision ID: 5c54ddca542f
Revises: 
Create Date: 2022-10-14 08:03:14.624049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c54ddca542f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilduserstatuses',
    sa.Column('internal_id', sa.String(length=500), nullable=False),
    sa.Column('guild_id', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=500), nullable=False),
    sa.Column('ends_at', sa.String(length=500), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('internal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guilduserstatuses')
    # ### end Alembic commands ###
